"""empty message

Revision ID: 6b9e5b5e235c
Revises: 
Create Date: 2020-11-18 11:36:38.811378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9e5b5e235c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groceries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesuares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_to_prepare', sa.String(), nullable=True),
    sa.Column('cooking_time', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_groceries',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('grocery_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Float(), nullable=True),
    sa.Column('mesuare_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_id'], ['groceries.id'], ),
    sa.ForeignKeyConstraint(['mesuare_id'], ['mesuares.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'grocery_id', 'mesuare_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_groceries')
    op.drop_table('recipes')
    op.drop_table('mesuares')
    op.drop_table('groceries')
    # ### end Alembic commands ###
